apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservico-barramento
spec:
  selector:
    matchLabels:
      app: microservico-barramento
  template:
    metadata:
      labels:
        app: microservico-barramento
    spec:
      containers:
      - name: microservico-barramento
        image: barramento
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
