apiVersion: v1
kind: Service
metadata:
  name: deploy-service-barramento
spec:
  selector:
    app: microservico-barramento
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodeport: 31110
  type: LoadBalancer
