apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservico-cadastros
spec:
  selector:
    matchLabels:
      app: microservico-cadastros
  template:
    metadata:
      labels:
        app: microservico-cadastros
    spec:
      containers:
      - name: microservico-cadastros
        image: cadastros
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000
